# Generated by Django 5.0.6 on 2024-07-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SWIMP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejemplo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
